// version.json byte-parity guard — B-135.
//
// `version.json` ships (sw.js precaches it) but is git-IGNORED (.gitignore:13),
// so it is never committed — it is GENERATED by two independent code paths that
// MUST agree byte-for-byte, or the precache manifest revision computed against
// one describes bytes the other serves:
//
//   * scripts/write-version-json.js  — the served copy (build-sw.js / task sw /
//     playwright webServer). AUTHORITATIVE payload definition.
//   * backend/Dockerfile              — the embedded copy, regenerated INSIDE the
//     image from the authoritative version.go Frontend constant.
//
// The original defect: the Node side wrote `JSON.stringify(payload) + '\n'`
// (21 bytes, trailing newline) and the Dockerfile wrote
// `printf '{"frontend":"%s"}'` (20 bytes, NO newline) — same JSON, different
// bytes, different md5. In prod the 20-byte Docker copy was served while sw.js's
// revision hashed the 21-byte Node copy.
//
// This test drives BOTH generators as they actually exist (it reads the printf
// format literal out of backend/Dockerfile, not a hand-copy) and asserts the
// bytes are identical. It is RED on the pre-fix Dockerfile and GREEN once the
// Dockerfile's printf gains the trailing \n.
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const FE_VERSION = '9.9.9-parity-probe'; // arbitrary; both sides must format it identically

// What scripts/write-version-json.js produces, byte-for-byte, for a given
// frontend version. We reproduce the module's write expression against a fixed
// version rather than shelling package.json so the test is deterministic and
// coupled to the code path, not the current release number.
function nodeGeneratorBytes(feVersion) {
  // Mirror scripts/write-version-json.js exactly: JSON.stringify(payload)+'\n'.
  // We assert below that the module's source still uses this expression, so a
  // future change there cannot silently drift past this test.
  const src = fs.readFileSync(path.join(ROOT, 'scripts', 'write-version-json.js'), 'utf8');
  expect(src).toContain("JSON.stringify(payload) + '\\n'");
  return Buffer.from(JSON.stringify({ frontend: feVersion }) + '\n', 'utf8');
}

// What backend/Dockerfile's `printf ... > version.json` produces, byte-for-byte.
// Extract the printf FORMAT literal from the Dockerfile itself (so this test
// tracks the real image build) and expand it with feVersion the way printf(1)
// would — literal text, %s substitution, and \n as a newline escape.
function dockerGeneratorBytes(feVersion) {
  const dockerfile = fs.readFileSync(path.join(ROOT, 'backend', 'Dockerfile'), 'utf8');
  // Match:  printf '<format>' "$fe_ver" > cmd/server/public/version.json
  const m = dockerfile.match(/printf\s+'([^']*)'\s+"\$fe_ver"\s*>\s*cmd\/server\/public\/version\.json/);
  expect(m, 'Dockerfile must still write version.json via a single-quoted printf format').not.toBeNull();
  const format = m[1];
  // Expand printf semantics we use: %s -> feVersion, \n -> newline. No other
  // escapes are present in this format; assert that so a new escape is not
  // silently mis-expanded.
  expect(format.replace('%s', '').replace(/\\n/g, '')).not.toMatch(/\\/);
  const expanded = format.replace('%s', feVersion).replace(/\\n/g, '\n');
  return Buffer.from(expanded, 'utf8');
}

function md5(buf) {
  return crypto.createHash('md5').update(buf).digest('hex');
}

test('version.json: the two generators produce byte-identical output', () => {
  const nodeBytes = nodeGeneratorBytes(FE_VERSION);
  const dockerBytes = dockerGeneratorBytes(FE_VERSION);

  // Surface the divergence loudly when it exists — this is the evidence line.
  const detail =
    `\n  node   : ${nodeBytes.length} bytes  md5=${md5(nodeBytes)}  ${JSON.stringify(nodeBytes.toString('utf8'))}` +
    `\n  docker : ${dockerBytes.length} bytes  md5=${md5(dockerBytes)}  ${JSON.stringify(dockerBytes.toString('utf8'))}`;

  expect(nodeBytes.length, `byte count must match:${detail}`).toBe(dockerBytes.length);
  expect(md5(nodeBytes), `md5 must match:${detail}`).toBe(md5(dockerBytes));
  expect(Buffer.compare(nodeBytes, dockerBytes), `bytes must be identical:${detail}`).toBe(0);
});
