// machine-xstate.mjs — the XState v5 candidate: the §19.1 scanner as a
// `type: 'parallel'` machine. Cross-region guards read a connectivity mirror
// kept in context by the connectivity region's entry actions (v5 inline
// guards receive only {context, event}; sibling-region state needs either
// stateIn() registered in setup() or a mirror).
//
// Revised in the missing-states deep dive (same sitting). Two findings shaped
// this file: (1) "go back to the interrupted state" cannot use XState history
// states (history applies when a compound state is re-entered; the scan
// region never exits), so DISMISS/resume are enumerated guarded transitions
// generated from a list — targets are static in XState, so a dynamic return
// needs one branch per returnable state; (2) the original parent-level
// QR_DECODED bubbling could not carry per-source return capture or the
// submitting/overrideConfirm exclusions, so the dedupe moved to per-state
// entries generated by a helper. Suite: js/conformance.mjs (18 sequences).

import { createMachine, createActor, assign } from 'xstate';

const INTERRUPTIBLE = [
  'resolving', 'offerReady', 'readyToSubmit', 'unknownCode', 'spentLocally',
  'expiredLocally', 'blockedOffline', 'overridePending', 'redeemed',
  'alreadyUsed', 'expired', 'notFound', 'error',
];

const RESET_CTX = {
  sessionCode: null, resolutionKind: null, requiresOnline: false,
  overrideAvailable: false, unverifiedWarning: false,
  gateReturn: null, promptReturn: null,
};

// Event alphabets per region — used only by the strict-mode experiment
// (strict-experiment.mjs): under broadcast semantics a region-level wildcard
// fires for every sibling-region event, so a usable tripwire must first
// whitelist the foreign alphabet.
const SCAN_EVENTS = [
  'SCAN', 'QR_DECODED', 'RESOLVED', 'ORDER_OK', 'SUBMIT',
  'OVERRIDE_REQUEST', 'OVERRIDE_CONFIRM', 'OVERRIDE_CANCEL', 'DISMISS',
  'RETRY', 'NEXT_CUSTOMER',
  'SRV_REDEEMED', 'SRV_ALREADY_USED', 'SRV_EXPIRED', 'SRV_NOT_FOUND', 'SRV_ERROR',
];
const CONN_EVENTS = ['CONN_DOWN', 'CONN_UP', 'PROBE_TIMEOUT', 'RESUBSCRIBED'];

// opts (all default off — the spike's green path is byte-identical without them):
//   strict: true          — region-root '*' wildcard whose action records the
//                           trip into opts.trips and THROWS (the v5 migration
//                           guide's replacement for v4 strict mode)
//   ignoreForeign: true   — region roots declare `{}` no-ops for the sibling
//                           region's alphabet (tier B of the experiment)
//   ignoreContracts: true — the suite-asserted deliberate ignores become
//                           explicit `{}` no-ops (tier C)
//   trips: []             — receives every tripwire hit for enumeration
export function createXstate(input, effects, opts = {}) {
  const emit = (e) => effects.push(e);
  const ignoreMap = (evs) => Object.fromEntries(evs.map((e) => [e, {}]));
  const strictOn = (region, foreign) => ({
    ...(opts.ignoreForeign ? ignoreMap(foreign) : {}),
    ...(opts.strict ? {
      '*': {
        actions: ({ event }) => {
          const msg = `${region} region: unhandled ${event.type}`;
          if (opts.trips) opts.trips.push(msg);
          throw new Error(msg);
        },
      },
    } : {}),
  });
  const contract = (map) => (opts.ignoreContracts ? map : {});

  // F6 dedupe for an interruptible state: same code → no-op; different code →
  // the finish-first prompt, remembering this state (self) to resume on
  // DISMISS. Each state names itself — a transition action cannot ask which
  // state it fired from.
  const interrupt = (self) => ({
    QR_DECODED: [
      { guard: ({ context, event }) => event.code === context.sessionCode },
      { target: 'promptFinishCurrent', actions: assign({ promptReturn: self }) },
    ],
  });
  const resettable = { NEXT_CUSTOMER: { target: 'idle', actions: assign(RESET_CTX) } };

  const resolvedKind = assign({
    resolutionKind: ({ event }) => event.kind,
    requiresOnline: ({ event }) => !!event.requiresOnline,
  });
  const submitOrGate = (self) => ({
    SUBMIT: [
      { guard: ({ context }) => context.conn === 'online', target: 'submitting', actions: () => emit({ type: 'submitToServer' }) },
      {
        target: 'blockedOffline',
        actions: assign({
          overrideAvailable: ({ context }) => context.canOverride && !context.requiresOnline,
          gateReturn: self,
        }),
      },
    ],
  });

  const machine = createMachine({
    id: 'scanner',
    type: 'parallel',
    context: {
      canOverride: false, ...input,
      conn: 'online', ...RESET_CTX,
    },
    states: {
      connectivity: {
        initial: 'online',
        on: strictOn('connectivity', SCAN_EVENTS),
        states: {
          online:  { entry: assign({ conn: 'online' }),  on: { CONN_DOWN: 'offline', PROBE_TIMEOUT: 'offline' } },
          offline: { entry: assign({ conn: 'offline' }), on: { CONN_UP: 'stale' } },
          stale:   { entry: assign({ conn: 'stale' }),   on: { RESUBSCRIBED: 'online', CONN_DOWN: 'offline', PROBE_TIMEOUT: 'offline' } },
        },
      },
      scan: {
        initial: 'idle',
        on: strictOn('scan', CONN_EVENTS),
        states: {
          idle: { on: { SCAN: 'scanning' } },
          scanning: {
            on: {
              QR_DECODED: {
                target: 'resolving',
                actions: assign({ sessionCode: ({ event }) => event.code }),
              },
            },
          },
          resolving: {
            on: {
              RESOLVED: [
                { guard: ({ event }) => event.kind === 'offerReady', target: 'offerReady', actions: resolvedKind },
                { guard: ({ event }) => event.kind === 'unknownCode', target: 'unknownCode', actions: resolvedKind },
                { // F3: online, the stale local flag does not reject — proceed, server decides
                  guard: ({ context, event }) => event.kind === 'spentLocally' && context.conn === 'online',
                  target: 'offerReady', actions: resolvedKind,
                },
                { guard: ({ event }) => event.kind === 'spentLocally', target: 'spentLocally', actions: resolvedKind },
                { guard: ({ event }) => event.kind === 'expiredLocally', target: 'expiredLocally', actions: resolvedKind },
              ],
              ...interrupt('resolving'),
              ...resettable,
            },
          },
          offerReady: { on: { ORDER_OK: 'readyToSubmit', ...interrupt('offerReady'), ...resettable, ...contract({ SUBMIT: {} }) } },
          readyToSubmit: { on: { ...submitOrGate('readyToSubmit'), ...interrupt('readyToSubmit'), ...resettable } },
          unknownCode: { on: { ...submitOrGate('unknownCode'), ...interrupt('unknownCode'), ...resettable } },
          blockedOffline: {
            on: {
              OVERRIDE_REQUEST: [
                {
                  guard: ({ context }) => context.overrideAvailable,
                  target: 'overrideConfirm',
                  actions: assign({ unverifiedWarning: ({ context }) => context.resolutionKind === 'unknownCode' }),
                },
                ...(opts.ignoreContracts ? [{}] : []),
              ],
              // P-KR4: reachability returned (RESUBSCRIBED while stale ⇒
              // connectivity lands online this same event) — resume the
              // pre-gate state. Targets are static, so one branch per source.
              RESUBSCRIBED: [
                { guard: ({ context }) => context.conn === 'stale' && context.gateReturn === 'readyToSubmit', target: 'readyToSubmit' },
                { guard: ({ context }) => context.conn === 'stale' && context.gateReturn === 'unknownCode', target: 'unknownCode' },
                ...(opts.ignoreContracts ? [{}] : []),
              ],
              ...interrupt('blockedOffline'),
              ...resettable,
            },
          },
          overrideConfirm: { // scans ignored mid-confirmation (no QR handler)
            on: {
              ...contract({ QR_DECODED: {}, NEXT_CUSTOMER: {} }),
              OVERRIDE_CONFIRM: {
                target: 'overridePending',
                actions: ({ context }) => emit({
                  type: 'writeAttempt',
                  offline_override: true,
                  unverified_code: context.resolutionKind === 'unknownCode',
                }),
              },
              OVERRIDE_CANCEL: 'blockedOffline',
            },
          },
          overridePending: { on: { ...interrupt('overridePending'), ...resettable } },
          submitting: { // mid-submit scans ignored — an in-flight verdict is never yanked (seq 17)
            on: {
              ...contract({ QR_DECODED: {}, NEXT_CUSTOMER: {} }),
              SRV_REDEEMED: 'redeemed', SRV_ALREADY_USED: 'alreadyUsed',
              SRV_EXPIRED: 'expired', SRV_NOT_FOUND: 'notFound', SRV_ERROR: 'error',
            },
          },
          promptFinishCurrent: {
            on: {
              QR_DECODED: [
                { guard: ({ context, event }) => event.code === context.sessionCode },
                {}, // a third code changes nothing — still finish the current customer
              ],
              DISMISS: [
                { // the gate resumed while prompting — return past it (P-KR4)
                  guard: ({ context }) => context.promptReturn === 'blockedOffline' && context.conn === 'online' && context.gateReturn === 'readyToSubmit',
                  target: 'readyToSubmit',
                },
                {
                  guard: ({ context }) => context.promptReturn === 'blockedOffline' && context.conn === 'online' && context.gateReturn === 'unknownCode',
                  target: 'unknownCode',
                },
                // dynamic "go back" needs static targets: one branch per state
                ...INTERRUPTIBLE.map((s) => ({ guard: ({ context }) => context.promptReturn === s, target: s })),
              ],
              ...resettable,
            },
          },
          redeemed: { on: { ...interrupt('redeemed'), ...resettable } },
          alreadyUsed: { on: { ...interrupt('alreadyUsed'), ...resettable } },
          spentLocally: { on: { ...interrupt('spentLocally'), ...resettable, ...contract({ SUBMIT: {} }) } },
          expiredLocally: { on: { ...interrupt('expiredLocally'), ...resettable } },
          expired: { on: { ...interrupt('expired'), ...resettable } },
          notFound: { on: { ...interrupt('notFound'), ...resettable } },
          error: {
            on: {
              RETRY: 'readyToSubmit', // failures are retryable; session intact
              ...interrupt('error'),
              ...resettable,
            },
          },
        },
      },
    },
  });

  const actor = createActor(machine);
  actor.start();

  return {
    send: (type, payload = {}) => actor.send({ type, ...payload }),
    conn: () => actor.getSnapshot().value.connectivity,
    scan: () => actor.getSnapshot().value.scan,
    flags: () => {
      const c = actor.getSnapshot().context;
      return { overrideAvailable: c.overrideAvailable, unverifiedWarning: c.unverifiedWarning };
    },
  };
}
