// spike-e1.spec.js — THROWAWAY spec for spike 01 of card E1 (identity-code-and-qr, D-KR3).
// Copied by the spike script into a worktree's tests/ directory and run there; never part of
// the suite. Self-contained on purpose (helpers re-stated from tests/marketing.spec.js).
//
// The images under test are tests/fixtures/spike-e1-<variant>.png, GENERATED by the spike
// script with the repo's own go-qrcode from the payloads in tests/fixtures/spike-e1-variants.json
// — server-made QRs, not hand-made fixtures. The first run of this spike showed the shipped
// reader answering `decodeError` for the 234-char hybrid payload at Medium/512 (version 11);
// html5-qrcode draws a picked file onto the hidden 320 px #scan-file-surface, so what matters is
// module DENSITY, not pixel size. This run measures which encodings the shipped reader decodes.
//
//   [E1-SPIKE-1] OFFLINE, nothing seeded — one test per variant: records kind + hash; PASSES when
//                the image decoded at all (kind !== decodeError) and the hash is the token's.
//                A compact descriptor the shipped reader cannot parse decodes to `unknownCode`
//                (still a decode); the full JSON descriptor decodes to `embeddedOffer`.
//   [E1-SPIKE-2] ONLINE — the first variant that decodes resolves the SERVER list → offerReady.
const { test, expect } = require('@playwright/test');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const ADMIN_EMAIL = 'jamal@yumyums.kitchen';
const ADMIN_PASSWORD = 'test123';
const MINT_SUB = 'spike-e1-mint-sub';
const CAMPAIGN_ID = 'a0000000-0000-4000-8000-000000000001';
const LABEL = 'Free side of wings';

const VARIANTS = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'spike-e1-variants.json'), 'utf8'));
const hashOf = (token) => crypto.createHash('sha256').update(token).digest('hex');

function campaignLowRow() {
  return { id: CAMPAIGN_ID, name: LABEL, requires_online: false, updated_at: '2026-09-01T00:00:00.000Z' };
}
function serverRow(id) {
  return { id, campaign_id: CAMPAIGN_ID, expires_at: '2028-01-01T00:00:00+00:00', redeemed_at: null, redeemed_by: null };
}
const isLookupUrl = (url) => url.pathname.endsWith('/sync/rest/codes') && url.searchParams.has('token_hash');

async function loginAs(page, email, password) {
  await page.goto('/login.html');
  await page.fill('input[type="email"]', email);
  await page.fill('input[type="password"]', password);
  await page.click('button.btn');
  await page.waitForURL((url) => !url.pathname.includes('login'));
}
async function mockSyncTransports(page) {
  await page.route('**/api/v1/sync/token', async (route) => {
    await route.fulfill({
      status: 200, contentType: 'application/json',
      body: JSON.stringify({ token: 'spike-bridge-token', expires_at: Math.floor(Date.now() / 1000) + 900, sub: MINT_SUB, role: 'authenticated', grants: ['marketing'] }),
    });
  });
  await page.route('**/sync/rest/**', async (route) => {
    const req = route.request();
    const u = new URL(req.url());
    if (req.method() === 'GET' && u.pathname.endsWith('/codes')) return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    if (req.method() === 'GET' && u.pathname.endsWith('/campaigns')) return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([campaignLowRow()]) });
    if (req.method() === 'POST' && u.pathname.endsWith('/scan_attempts')) return route.fulfill({ status: 201, contentType: 'application/json', body: '' });
    return route.fulfill({ status: 503, body: 'unmocked sync transport' });
  });
}
async function openScanner(page) {
  await loginAs(page, ADMIN_EMAIL, ADMIN_PASSWORD);
  await page.goto('/marketing.html');
  await page.waitForFunction(() => window.MarketingScan && window.MarketingScan.booted === true);
}
async function scanImage(page, fixtureFile) {
  await page.setInputFiles('#scan-file', path.join(__dirname, 'fixtures', fixtureFile));
  await page.waitForSelector('#scan-result[data-kind]', { state: 'attached' });
}
async function readResult(page) {
  const r = page.locator('#scan-result');
  return { kind: await r.getAttribute('data-kind'), hash: await r.getAttribute('data-token-hash'), source: await r.getAttribute('data-source') };
}

test.describe('spike E1 — server-generated hybrid QRs through the shipped scanner (D-KR3)', () => {
  for (const v of VARIANTS) {
    test(`[E1-SPIKE-1-${v.name}] OFFLINE: ${v.desc}`, async ({ page }) => {
      await openScanner(page);
      await page.context().setOffline(true);
      await scanImage(page, `spike-e1-${v.name}.png`);
      const got = await readResult(page);
      const ok = got.kind !== 'decodeError' && got.hash === hashOf(v.token);
      console.log('SPIKE-E1-VARIANT ' + JSON.stringify({ name: v.name, decoded: ok, kind: got.kind, hash_ok: got.hash === hashOf(v.token), ...v.enc }));
      expect(ok, `${v.name}: kind=${got.kind}`).toBe(true);
      if (v.fullDescriptor) {
        await expect(page.locator('#scan-result')).toHaveAttribute('data-kind', 'embeddedOffer');
        await expect(page.locator('#scan-result')).toContainText(LABEL);
      }
    });
  }

  test('[E1-SPIKE-2] ONLINE: the first decodable variant resolves the SERVER list → offerReady', async ({ page }) => {
    await mockSyncTransports(page);
    await page.route(isLookupUrl, (route) => route.fulfill({
      status: 200, contentType: 'application/json',
      body: JSON.stringify([serverRow('e1000000-0000-4000-8000-000000000001')]),
    }));
    let chosen = null;
    for (const v of VARIANTS) {
      await openScanner(page);
      await page.waitForFunction(() => window.MarketingSubmit && window.MarketingSubmit.booted === true);
      await page.waitForFunction(() => document.getElementById('scan-status').textContent.includes('Replica synced'));
      await expect(page.locator('#scan-conn')).toHaveAttribute('data-conn', 'online');
      await scanImage(page, `spike-e1-${v.name}.png`);
      await page.waitForFunction(() => document.getElementById('scan-result').getAttribute('data-kind') !== 'checkingServer', null, { timeout: 10000 });
      const got = await readResult(page);
      // A decode that did not yield THIS token's hash (decodeError, or a corrupted read
      // such as invalidPayload) is not a decode — skip it.
      if (got.hash !== hashOf(v.token)) continue;
      chosen = { v, got };
      break;
    }
    console.log('SPIKE-E1-ONLINE ' + JSON.stringify(chosen ? { name: chosen.v.name, ...chosen.got } : { none: true }));
    expect(chosen, 'no variant decoded online').not.toBeNull();
    expect(chosen.got.kind).toBe('offerReady');
    expect(chosen.got.source).toBe('server');
    expect(chosen.got.hash).toBe(hashOf(chosen.v.token));
  });
});
